### ISSUE TITLE
tornado.application: Exception in callback funcools. 

### ISSUE THREAD

**Issue by Frikster** [bokeh/bokeh-demos#18]
Hi @birdsarah , I followed the instructions as per the readme. I have the app running at http://127.0.0.1:8000/ but when I (do only this and nothing else) click on a user the server terminal immediately displays this error: 

Running:
![screenshot from 2016-01-08 19 18 52](https://cloud.githubusercontent.com/assets/10172142/12214108/ba0b2d4c-b63c-11e5-9516-c9567dd38a6d.png)

Clicked Adelaida
![screenshot from 2016-01-08 19 22 32](https://cloud.githubusercontent.com/assets/10172142/12214120/35a605f8-b63d-11e5-8737-7e9f80d9056c.png)

When I then go on to try and add happiness to Adelaida, the manager responds correctly with POST and GET but nothing is updated on the browser and I get more error messages (everything attached below). Same issue with other users.

Thanx in advance for any assistance

server traceback **before** clicking Adelaida's name
    
    cornelis@Bob:~$ cd PycharmProjects/bokeh-demos/happiness/
    cornelis@Bob:~/PycharmProjects/bokeh-demos/happiness$ conda create -n happiness --file conda-requirements.txt
    Error: prefix already exists: /home/cornelis/anaconda3/envs/happiness
    cornelis@Bob:~/PycharmProjects/bokeh-demos/happiness$ source activate happiness
    discarding /home/cornelis/anaconda3/bin from PATH
    prepending /home/cornelis/anaconda3/envs/happiness/bin to PATH
    (happiness)cornelis@Bob:~/PycharmProjects/bokeh-demos/happiness$ ./bokeh.sh
    INFO:bokeh.command.subcommands.serve:Starting Bokeh server on port 5006 with applications at paths ['/individual', '/individuals', '/team', '/teams']
    INFO:bokeh.server.views.ws:WebSocket connection opened
    INFO:bokeh.server.views.ws:ServerConnection created
    ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f68dc88e1e0>, <tornado.concurrent.Future object at 0x7f68dbe79630>)
    Traceback (most recent call last):
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/ioloop.py", line 600, in _run_callback
        ret = callback()
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/ioloop.py", line 615, in <lambda>
        self.add_future(ret, lambda f: f.result())
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/gen.py", line 1017, in run
        yielded = self.gen.send(value)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/server/session.py", line 42, in _needs_document_lock_wrapper
        result = yield yield_for_all_futures(func(self, *args, **kwargs))
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/server/session.py", line 145, in with_document_locked
        return func(*args, **kwargs)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 488, in wrapper
        return doc._with_self_as_curdoc(invoke)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 479, in _with_self_as_curdoc
        return f()
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 487, in invoke
        return f(*args, **kwargs)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 879, in remove_then_invoke
        return callback(*args, **kwargs)
      File "/home/cornelis/PycharmProjects/bokeh-demos/happiness/viz/individual.py", line 37, in update_data_once
        update_data()
      File "/home/cornelis/PycharmProjects/bokeh-demos/happiness/viz/individual.py", line 22, in update_data
        user_pk = document.get_model_by_name('user_pk_source').data['user_pk'][0]
    IndexError: list index out of range
    INFO:bokeh.server.views.ws:WebSocket connection opened
    INFO:bokeh.server.views.ws:ServerConnection created
    ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f68dbdf3488>, <tornado.concurrent.Future object at 0x7f68dbe79b38>)
    Traceback (most recent call last):
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/ioloop.py", line 600, in _run_callback
        ret = callback()
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/ioloop.py", line 615, in <lambda>
        self.add_future(ret, lambda f: f.result())
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/gen.py", line 1017, in run
        yielded = self.gen.send(value)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/server/session.py", line 42, in _needs_document_lock_wrapper
        result = yield yield_for_all_futures(func(self, *args, **kwargs))
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/server/session.py", line 145, in with_document_locked
        return func(*args, **kwargs)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 488, in wrapper
        return doc._with_self_as_curdoc(invoke)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 479, in _with_self_as_curdoc
        return f()
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 487, in invoke
        return f(*args, **kwargs)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 879, in remove_then_invoke
        return callback(*args, **kwargs)
      File "/home/cornelis/PycharmProjects/bokeh-demos/happiness/viz/individuals.py", line 56, in update_data_once
        update_data()
      File "/home/cornelis/PycharmProjects/bokeh-demos/happiness/viz/individuals.py", line 29, in update_data
        user_pk = document.get_model_by_name('user_pk_source').data['user_pk'][0]
    IndexError: list index out of range
    INFO:tornado.access:200 GET /individuals/autoload.js?bokeh-autoload-element=d0e24748-b376-4470-bc0b-57f1724895ae&bokeh-session-id=XGQjKlE7Fy6F9vf3vPq0fjscSKlRHZRxOvEAcz1KAarY (127.0.0.1) 11.66ms
    INFO:tornado.access:200 GET /individual/autoload.js?bokeh-autoload-element=916d9300-77c5-48ad-9085-855fe928ad14&bokeh-session-id=ZnUX9HjMsjs80PYiEMu8bt2ywn5ejsZlNTGv9BcZ4TpJ (127.0.0.1) 2.26ms
    ERROR:bokeh.server.views.ws:Refusing websocket connection from Origin 'http://127.0.0.1:8000'; use --allow-websocket-origin=127.0.0.1:8000 to permit this; currently we allow origins False
    WARNING:tornado.access:403 GET /individual/ws?bokeh-protocol-version=1.0&bokeh-session-id=ZnUX9HjMsjs80PYiEMu8bt2ywn5ejsZlNTGv9BcZ4TpJ (127.0.0.1) 0.62ms
    ERROR:bokeh.server.views.ws:Refusing websocket connection from Origin 'http://127.0.0.1:8000'; use --allow-websocket-origin=127.0.0.1:8000 to permit this; currently we allow origins False
    WARNING:tornado.access:403 GET /individuals/ws?bokeh-protocol-version=1.0&bokeh-session-id=XGQjKlE7Fy6F9vf3vPq0fjscSKlRHZRxOvEAcz1KAarY (127.0.0.1) 0.93ms
   
And here is the server traceback that comes out immediately after I click her name and add happiness 5

    Setting up django
    INFO:bokeh.server.views.ws:WebSocket connection opened
    INFO:bokeh.server.views.ws:ServerConnection created
    ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f68dbdb46a8>, <tornado.concurrent.Future object at 0x7f68db967c50>)
    Traceback (most recent call last):
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/ioloop.py", line 600, in _run_callback
        ret = callback()
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/ioloop.py", line 615, in <lambda>
        self.add_future(ret, lambda f: f.result())
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/gen.py", line 1017, in run
        yielded = self.gen.send(value)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/server/session.py", line 42, in _needs_document_lock_wrapper
        result = yield yield_for_all_futures(func(self, *args, **kwargs))
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/server/session.py", line 145, in with_document_locked
        return func(*args, **kwargs)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 488, in wrapper
        return doc._with_self_as_curdoc(invoke)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 479, in _with_self_as_curdoc
        return f()
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 487, in invoke
        return f(*args, **kwargs)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 879, in remove_then_invoke
        return callback(*args, **kwargs)
      File "/home/cornelis/PycharmProjects/bokeh-demos/happiness/viz/individual.py", line 37, in update_data_once
        update_data()
      File "/home/cornelis/PycharmProjects/bokeh-demos/happiness/viz/individual.py", line 22, in update_data
        user_pk = document.get_model_by_name('user_pk_source').data['user_pk'][0]
    IndexError: list index out of range
    INFO:bokeh.server.views.ws:WebSocket connection opened
    INFO:bokeh.server.views.ws:ServerConnection created
    ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f68dba7aa60>, <tornado.concurrent.Future object at 0x7f68dba19c88>)
    Traceback (most recent call last):
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/ioloop.py", line 600, in _run_callback
        ret = callback()
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/ioloop.py", line 615, in <lambda>
        self.add_future(ret, lambda f: f.result())
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/tornado/gen.py", line 1017, in run
        yielded = self.gen.send(value)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/server/session.py", line 42, in _needs_document_lock_wrapper
        result = yield yield_for_all_futures(func(self, *args, **kwargs))
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/server/session.py", line 145, in with_document_locked
        return func(*args, **kwargs)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 488, in wrapper
        return doc._with_self_as_curdoc(invoke)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 479, in _with_self_as_curdoc
        return f()
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 487, in invoke
        return f(*args, **kwargs)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 879, in remove_then_invoke
        return callback(*args, **kwargs)
      File "/home/cornelis/PycharmProjects/bokeh-demos/happiness/viz/individuals.py", line 56, in update_data_once
        update_data()
      File "/home/cornelis/PycharmProjects/bokeh-demos/happiness/viz/individuals.py", line 29, in update_data
        user_pk = document.get_model_by_name('user_pk_source').data['user_pk'][0]
    IndexError: list index out of range
    INFO:tornado.access:200 GET /individuals/autoload.js?bokeh-autoload-element=89c8a413-4617-4d92-a722-7111302b5a97&bokeh-session-id=oWxqIWm0THA0vfZDTY8S41vnleoi8jfG7DBOnqHcKGPm (127.0.0.1) 2.65ms
    INFO:tornado.access:200 GET /individual/autoload.js?bokeh-autoload-element=cc9b8b65-0d5a-4cc8-8f2d-1ce6ca0b230b&bokeh-session-id=J2NowcxBeLWRuKN0PeL7tBPjwXuRkiQceWJ7ORpLyiz5 (127.0.0.1) 2.21ms
    ERROR:bokeh.server.views.ws:Refusing websocket connection from Origin 'http://127.0.0.1:8000'; use --allow-websocket-origin=127.0.0.1:8000 to permit this; currently we allow origins False
    WARNING:tornado.access:403 GET /individual/ws?bokeh-protocol-version=1.0&bokeh-session-id=J2NowcxBeLWRuKN0PeL7tBPjwXuRkiQceWJ7ORpLyiz5 (127.0.0.1) 0.59ms
    ERROR:bokeh.server.views.ws:Refusing websocket connection from Origin 'http://127.0.0.1:8000'; use --allow-websocket-origin=127.0.0.1:8000 to permit this; currently we allow origins False
    WARNING:tornado.access:403 GET /individuals/ws?bokeh-protocol-version=1.0&bokeh-session-id=oWxqIWm0THA0vfZDTY8S41vnleoi8jfG7DBOnqHcKGPm (127.0.0.1) 1.15ms

Manager:

    cornelis@Bob:~$ cd PycharmProjects/bokeh-demos/happiness/
    cornelis@Bob:~/PycharmProjects/bokeh-demos/happiness$ ./manage.py runserverPerforming system checks...
    
    System check identified no issues (0 silenced).
    January 09, 2016 - 03:18:32
    Django version 1.9.1, using settings 'webapp.settings'
    Starting development server at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.
    [09/Jan/2016 03:18:39] "GET / HTTP/1.1" 200 8420
    [09/Jan/2016 03:20:19] "GET /5/individual/ HTTP/1.1" 200 5677
    [09/Jan/2016 03:23:14] "POST /5/add_happiness/ HTTP/1.1" 302 0
    [09/Jan/2016 03:23:15] "GET /5/individual/ HTTP/1.1" 200 5677

**Comment by Frikster** [comment]
I did try --allow-websocket-origin=127.0.0.1:8000 as follows. Maybe I'm doing it wrong? I still get the same error

cornelis@Bob:~/PycharmProjects/bokeh-demos/happiness$ source activate happinessdiscarding /home/cornelis/anaconda3/bin from PATH
prepending /home/cornelis/anaconda3/envs/happiness/bin to PATH
(happiness)cornelis@Bob:~/PycharmProjects/bokeh-demos/happiness$ ./bokeh.sh --allow-websocket-origin=127.0.0.1:8000 
INFO:bokeh.command.subcommands.serve:Starting Bokeh server on port 5006 with applications at paths ['/individual', '/individuals', '/team', '/teams']

and then when launching from browser I get what looks like the usual jelly:
INFO:bokeh.server.views.ws:WebSocket connection opened
INFO:bokeh.server.views.ws:ServerConnection created
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fb5877321e0>, <tornado.concurrent.Future object at 0x7fb586d1d630>)
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fb5877321e0>, <tornado.concurrent.Future object at 0x7fb586d1d630>)
Traceback (most recent call last):
etc...

**Comment by bryevdv** [comment]
I don't actually think this is a Bokeh issue, per se. 
```
File "/home/cornelis/PycharmProjects/bokeh-demos/happiness/viz/individuals.py", line 29, in update_data
    user_pk = document.get_model_by_name('user_pk_source').data['user_pk'][0]
IndexError: list index out of range
```
tells me the data being asked for in the db table is not being found. I might try to poke at this tomorrow too.

**Comment by birdsarah** [comment]
Hi @Frikster, sorry for my slow response, this issue slipped me by.

One thing that's weird about your report is all the errors that read ``ERROR:tornado.application:Exception in callback functools.partial(.null_wrapper at 0x7fb5877321e0>, )`` - can you double check that you're using the released version of bokeh 0.11.0 (maybe try a clean environment).

However, that doesn't preclude your issues.

My apologies, the README was out of date and you should have been running on 8001, I had an open PR with an updated the README. I've just gone ahead and merged it so if you pull master of bokeh-demos hopefully things will be working.

Alternatively, if you want to run django on the default 8000, you can edit `bokeh.sh` and alter the 
`--host` argument. I haven't got `--allow-websocket-origin` to do anything, I think what you want is the `--host` argument.

The code could have been made more robust against this error. My apologies. I've asked for a code review so hopefully we can keep making this example better.

One thing to note is that the origin of this problem is not what @bryevdv suggested. Here's what was happening.

- The bokeh session doesn't know which user it is generating a plot for. 
- The django views code creates a new session and populates it with a user id that the bokeh server can use to generate the data for the plot.
- The bokeh session can then go about its business creating and updating the plot

To populate the user id, we use a ColumnDataSource, this is kind of hacky and there's an open issue to allow more elegant ways of doing this - such as session parameters.

Because we're using a column data source, the bokeh code calls

    user_pk = document.get_model_by_name('user_pk_source').data['user_pk'][0]

grabbing the only item from the data source that we've used to pass the id around. If the data source is empty, then the `IndexError` occurs.

I believe that because you didn't have permissions set up correctly between django and bokeh, django wasn't able to populate the session and that caused the data source to be empty.

As I said, hopefully this should all be fixed in master. Please let us know how you get on and I'll try and be more responsive next time. Thank you for your patience.

**Comment by Frikster** [comment]
@birdsarah 

>One thing that's weird about your report is all the errors that read >ERROR:tornado.application:Exception in callback functools.partial(.null_wrapper at >0x7fb5877321e0>, ) - can you double check that you're using the released version of bokeh 0.11.0 >(maybe try a clean environment).

I deleted the happiness folder in home/anaconda3/envs and started from scratch. Also:
>cornelis@Bob:~$ bokeh --version
>0.11.0

new error now with `--host=localhost:8001 in bokeh.sh` (I didn't modify it). 
**ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory**

    cornelis@Bob:~$ cd PycharmProjects/bokeh-demos/happiness/
    cornelis@Bob:~/PycharmProjects/bokeh-demos/happiness$ conda create -n happiness --file conda-requirements.txt
    Fetching package metadata: ....
    Solving package specifications: 
    Package plan for installation in environment /home/cornelis/anaconda3/envs/happiness:

    The following NEW packages will be INSTALLED:

    backports_abc:   0.4-py34_0        
    bokeh:           0.11.0-py34_1     
    django:          1.8.4-py34_0      
    flask:           0.10.1-py34_1     
    itsdangerous:    0.24-py34_0       
    jinja2:          2.8-py34_0        
    markupsafe:      0.23-py34_0       
    numpy:           1.10.1-py34_0     
    openssl:         1.0.2d-0          
    pandas:          0.17.1-np110py34_0
    pip:             7.1.2-py34_0      
    python:          3.4.3-2           
    python-dateutil: 2.4.2-py34_0      
    pytz:            2015.7-py34_0     
    pyyaml:          3.11-py34_1       
    pyzmq:           14.7.0-py34_1     
    readline:        6.2-2             
    requests:        2.8.1-py34_0      
    setuptools:      18.5-py34_0       
    six:             1.10.0-py34_0     
    sqlite:          3.8.4.1-1         
    tk:              8.5.18-0          
    tornado:         4.3-py34_0        
    werkzeug:        0.11.2-py34_0     
    wheel:           0.26.0-py34_1     
    xz:              5.0.5-0           
    yaml:            0.1.6-0           
    zeromq:          4.1.3-0           
    zlib:            1.2.8-0           

    Proceed ([y]/n)? Y

    Linking packages ...
    [      COMPLETE      ]|###################################################| 100%
    #
    # To activate this environment, use:
    # $ source activate happiness
    # 
    # To deactivate this environment, use:
    # $ source deactivate
    #
    cornelis@Bob:~/PycharmProjects/bokeh-demos/happiness$ source activate happinessdiscarding /home/cornelis/anaconda3/bin from PATH
    prepending /home/cornelis/anaconda3/envs/happiness/bin to PATH
    (happiness)cornelis@Bob:~/PycharmProjects/bokeh-demos/happiness$ ./bokeh.shTraceback (most recent call last):
      File "/home/cornelis/anaconda3/envs/happiness/bin/bokeh", line 5, in <module>
    from bokeh.command.bootstrap import main
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/command/__init__.py", line 15, in <module>
    _build_docstring()
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/command/__init__.py", line 10, in _build_docstring
    from . import subcommands
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/command/subcommands/__init__.py", line 29, in <module>
    all = _collect()
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/command/subcommands/__init__.py", line 17, in _collect
    mod = import_module("." + modname, __package__)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/command/subcommands/file_output.py", line 12, in <module>
    from ..util import build_single_handler_applications, die
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/command/util.py", line 9, in <module>
    from bokeh.application import Application
     File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/application/__init__.py", line 3, in <module>
    from .application import Application
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/application/application.py", line 14, in <module>
    from ..util.tornado import yield_for_all_futures
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/util/tornado.py", line 11, in <module>
    from bokeh.document import NextTickCallback, PeriodicCallback, TimeoutCallback
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/document.py", line 16, in <module>
    from .core.json_encoder import serialize_json
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/bokeh/core/json_encoder.py", line 14, in <module>
    import numpy as np
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
      File "/home/cornelis/anaconda3/envs/happiness/lib/python3.4/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
    ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
    (happiness)cornelis@Bob:~/PycharmProjects/bokeh-demos/happiness$ 

Please let me know if I'm doing something wrong. I'm not sure whether

>Alternatively, if you want to run django on the default 8000, you can edit bokeh.sh and alter the
>--host argument. I haven't got --allow-websocket-origin to do anything, I think what you want is the >--host argument.

I changed the --host argument in bokeh.sh back to 8000 but the same error. Is this an issue on my end or something else? Thanx

**Comment by birdsarah** [comment]
Maybe try `conda env remove -n happiness`

And then try re-installing the env again. This is not my area.

**Comment by birdsarah** [comment]
I'm closing this as I believe the original issue is resolved.
